package com.rork.whispercell.models

/** Global performer settings. Provider keys are held in memory only in this preview build. */
data class AppSettings(
    val startPhraseEnabled: Boolean = true,
    val startPhrases: List<String> = listOf("Picture this clearly for me"),
    val stopPhraseEnabled: Boolean = true,
    val stopPhrases: List<String> = listOf("Perfect"),
    val removeStartAndStopPhrases: Boolean = true,
    val silenceBehavior: SilenceBehavior = SilenceBehavior.Ignore,
    val maximumCaptureSeconds: Int = 90,
    val manualBackupEnabled: Boolean = true,
    val selectedSpeechProviderId: String = "android_builtin",
    val openAiTranscriptionEnabled: Boolean = false,
    val openAiApiKey: String = "",
    val openAiModel: String = "gpt-4o-mini-transcribe",
    val openAiRealtimeEnabled: Boolean = false,
    val openAiChunkEnabled: Boolean = true,
    val openAiValidationStatus: String = "Not configured",
    val elevenLabsEnabled: Boolean = false,
    val elevenLabsApiKey: String = "",
    val elevenLabsModel: String = "scribe_v1",
    val elevenLabsValidationStatus: String = "Not configured",
    val language: String = "en-US",
    val cleanTranscriptMode: Boolean = true,
    val verbatimTranscriptMode: Boolean = false,
    val injectEnabled: Boolean = true,
    val selectionCode: String = "",
    val injectTimeoutSeconds: Int = 8,
    val injectRetryOnce: Boolean = false,
    val reviewModeEnabled: Boolean = true,
    val fullAutomationEnabled: Boolean = false,
    val audioSavingEnabled: Boolean = false,
    val transcriptSavePolicy: String = "Current session only",
    val keepLogsFor24Hours: Boolean = false,
    val autoStartSessionWhenAppOpens: Boolean = false,
    val continueListeningAfterPublish: Boolean = true
)
